# Generated by Django 5.0.6 on 2024-07-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_streamingplatform_watch_delete_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
