# Generated by Django 5.0.6 on 2024-07-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_watch_avg_rating_watch_total_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watch',
            options={'ordering': ['-created']},
        ),
    ]
