# Generated by Django 5.0.6 on 2024-07-21 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_watch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.watch')),
            ],
        ),
    ]
