# Generated by Django 5.0.6 on 2024-07-21 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='watch',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app1.category'),
            preserve_default=False,
        ),
    ]
