# Generated by Django 5.0.6 on 2024-07-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_category_options_remove_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='screenshots',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
