# Generated by Django 5.0.6 on 2025-04-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_watch_screenshots_watch_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
